/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package showmilhao;

public class Convidados extends javax.swing.JFrame {
    char[] convidados = new char[4];
    
    public Convidados(char convidados[]) {
        initComponents();   
        this.convidados = convidados;
        adicionarTexto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(372, 220));
        setMinimumSize(new java.awt.Dimension(372, 220));
        getContentPane().setLayout(null);

        label1.setBackground(new java.awt.Color(255, 255, 255));
        label1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("A");
        label1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        label1.setMaximumSize(new java.awt.Dimension(34, 14));
        label1.setMinimumSize(new java.awt.Dimension(34, 14));
        label1.setOpaque(true);
        getContentPane().add(label1);
        label1.setBounds(10, 100, 70, 60);

        label2.setBackground(new java.awt.Color(255, 255, 255));
        label2.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label2.setText("A");
        label2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        label2.setMaximumSize(new java.awt.Dimension(34, 14));
        label2.setMinimumSize(new java.awt.Dimension(34, 14));
        label2.setOpaque(true);
        getContentPane().add(label2);
        label2.setBounds(100, 100, 70, 60);

        label3.setBackground(new java.awt.Color(255, 255, 255));
        label3.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label3.setText("A");
        label3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        label3.setMaximumSize(new java.awt.Dimension(34, 14));
        label3.setMinimumSize(new java.awt.Dimension(34, 14));
        label3.setOpaque(true);
        getContentPane().add(label3);
        label3.setBounds(190, 100, 70, 60);

        label4.setBackground(new java.awt.Color(255, 255, 255));
        label4.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label4.setText("A");
        label4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        label4.setMaximumSize(new java.awt.Dimension(34, 14));
        label4.setMinimumSize(new java.awt.Dimension(34, 14));
        label4.setOpaque(true);
        getContentPane().add(label4);
        label4.setBounds(280, 100, 70, 60);

        jLabel2.setBackground(new java.awt.Color(255, 0, 51));
        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ajuda de nossos convidados");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 30, 340, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/showmilhão/13115545492078.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 370, 200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    public void adicionarTexto(){
        label1.setText(String.valueOf(convidados[0]));
        label2.setText(String.valueOf(convidados[1]));
        label3.setText(String.valueOf(convidados[2]));
        label4.setText(String.valueOf(convidados[3]));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    // End of variables declaration//GEN-END:variables
}
