/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package showmilhao;

/**
 *
 * @author Gabriel_PC
 */
public class Placas extends javax.swing.JFrame {
    char placas[] = new char[8];
    /**
     * Creates new form Placas
     */
    public Placas(char placas[]) {
        initComponents();
        this.placas = placas;
        adicionarTexto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label5 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        label8 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(420, 300));
        setMinimumSize(new java.awt.Dimension(420, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        label5.setBackground(new java.awt.Color(255, 255, 255));
        label5.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        label5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label5.setText("A");
        label5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        label5.setOpaque(true);
        getContentPane().add(label5);
        label5.setBounds(40, 170, 70, 60);

        label4.setBackground(new java.awt.Color(255, 255, 255));
        label4.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label4.setText("A");
        label4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        label4.setMaximumSize(new java.awt.Dimension(34, 14));
        label4.setMinimumSize(new java.awt.Dimension(34, 14));
        label4.setOpaque(true);
        getContentPane().add(label4);
        label4.setBounds(280, 90, 70, 60);

        label6.setBackground(new java.awt.Color(255, 255, 255));
        label6.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        label6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label6.setText("A");
        label6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        label6.setMaximumSize(new java.awt.Dimension(34, 14));
        label6.setMinimumSize(new java.awt.Dimension(34, 14));
        label6.setOpaque(true);
        getContentPane().add(label6);
        label6.setBounds(120, 170, 70, 60);

        label3.setBackground(new java.awt.Color(255, 255, 255));
        label3.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label3.setText("A");
        label3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        label3.setMaximumSize(new java.awt.Dimension(34, 14));
        label3.setMinimumSize(new java.awt.Dimension(34, 14));
        label3.setOpaque(true);
        getContentPane().add(label3);
        label3.setBounds(200, 90, 70, 60);

        label1.setBackground(new java.awt.Color(255, 255, 255));
        label1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("A");
        label1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        label1.setOpaque(true);
        getContentPane().add(label1);
        label1.setBounds(40, 90, 70, 60);

        label7.setBackground(new java.awt.Color(255, 255, 255));
        label7.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        label7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label7.setText("A");
        label7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        label7.setMaximumSize(new java.awt.Dimension(34, 14));
        label7.setMinimumSize(new java.awt.Dimension(34, 14));
        label7.setOpaque(true);
        getContentPane().add(label7);
        label7.setBounds(200, 170, 70, 60);

        label8.setBackground(new java.awt.Color(255, 255, 255));
        label8.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        label8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label8.setText("A");
        label8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        label8.setMaximumSize(new java.awt.Dimension(34, 14));
        label8.setMinimumSize(new java.awt.Dimension(34, 14));
        label8.setOpaque(true);
        getContentPane().add(label8);
        label8.setBounds(280, 170, 70, 60);

        label2.setBackground(new java.awt.Color(255, 255, 255));
        label2.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label2.setText("A");
        label2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        label2.setMaximumSize(new java.awt.Dimension(34, 14));
        label2.setMinimumSize(new java.awt.Dimension(34, 14));
        label2.setOpaque(true);
        getContentPane().add(label2);
        label2.setBounds(120, 90, 70, 60);

        jLabel2.setBackground(new java.awt.Color(255, 0, 51));
        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Veja abaixo o que a platéia têm a dizer");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 30, 310, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/showmilhão/13115545492078.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 450, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void adicionarTexto(){
        label1.setText(String.valueOf(placas[0]));
        label2.setText(String.valueOf(placas[1]));
        label3.setText(String.valueOf(placas[2]));
        label4.setText(String.valueOf(placas[3]));
        label5.setText(String.valueOf(placas[4]));
        label6.setText(String.valueOf(placas[5]));
        label7.setText(String.valueOf(placas[6]));
        label8.setText(String.valueOf(placas[7]));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    // End of variables declaration//GEN-END:variables
}
