/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package showmilhao;

import Classes.Jogador;
import Classes.Perguntas;
import showmilhão.TelaPrincipal;

import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel_PC
 */
public class telaInicial extends javax.swing.JFrame {
    Perguntas possiveis[];
    Jogador qtdJogador[];
    Jogador j = new Jogador();
    /**
     * Creates new form telaInicial
     */
    public telaInicial(Perguntas possiveis[], Jogador qtdJogador[]) {
        initComponents();
        this.possiveis = possiveis;
        this.qtdJogador = qtdJogador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastrar = new javax.swing.JButton();
        verificar = new javax.swing.JButton();
        iniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(362, 352));
        setMinimumSize(new java.awt.Dimension(362, 352));
        getContentPane().setLayout(null);

        cadastrar.setBackground(new java.awt.Color(255, 0, 51));
        cadastrar.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        cadastrar.setForeground(new java.awt.Color(255, 255, 255));
        cadastrar.setText("Cadastrar Jogador");
        cadastrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrar);
        cadastrar.setBounds(50, 120, 260, 40);

        verificar.setBackground(new java.awt.Color(255, 0, 51));
        verificar.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        verificar.setForeground(new java.awt.Color(255, 255, 255));
        verificar.setText("Verificar pontuações");
        verificar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        verificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificarActionPerformed(evt);
            }
        });
        getContentPane().add(verificar);
        verificar.setBounds(50, 180, 260, 40);

        iniciar.setBackground(new java.awt.Color(255, 0, 51));
        iniciar.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        iniciar.setForeground(new java.awt.Color(255, 255, 255));
        iniciar.setText("Iniciar jogo");
        iniciar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });
        getContentPane().add(iniciar);
        iniciar.setBounds(50, 240, 260, 40);

        jLabel1.setBackground(new java.awt.Color(255, 0, 51));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Escolha uma das opções");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 50, 260, 40);

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/showmilhao/13115545492078.jpg"))); // NOI18N
        getContentPane().add(fundo);
        fundo.setBounds(0, 0, 360, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificarActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios(qtdJogador).setVisible(true);
            }
        });
    }//GEN-LAST:event_verificarActionPerformed

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
        
        String nome = JOptionPane.showInputDialog(null, "Entre com o seu nickname");
        
        
        for(int i=0;i<qtdJogador.length;i++)
        {
            if(qtdJogador[i].getNickName().equals(nome))
            {
                j=qtdJogador[i];
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        
                        new showmilhao.TelaPrincipal(possiveis, j, telaInicial.this).setVisible(true);
                   }
        });
            }
        }
        
        
        
        this.setVisible(false);
    }//GEN-LAST:event_iniciarActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarJogador(qtdJogador).setVisible(true);
            }
        });
    }//GEN-LAST:event_cadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrar;
    private javax.swing.JLabel fundo;
    private javax.swing.JButton iniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton verificar;
    // End of variables declaration//GEN-END:variables
}
