/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package showmilhao;

import Classes.Jogador;
import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author Gabriel_PC
 */
public class Usuarios extends javax.swing.JFrame {

    private JLabel nome[] = new JLabel[10];
    private JLabel nick[] = new JLabel[10];
    private JLabel premio[] = new JLabel[10];
    /**
     * Creates new form Usuários
     */
    public Usuarios(Jogador qtdJogadores[]) {
        initComponents();
        criaForm(qtdJogadores);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public void criaForm(Jogador qtdjogadores[]){
        int x = 50;
        this.getContentPane().setBackground(Color.blue);
        JLabel nometitulo = new JLabel("NOME");
        JLabel nicktitulo = new JLabel("NICKNAME");
        JLabel premiotitulo = new JLabel("PRÊMIO");
        nometitulo.setBounds(80, 0, 150, 50);
        nicktitulo.setBounds(245, 0, 150, 50);
        premiotitulo.setBounds(430, 0, 150, 50);
        
        getContentPane().add(nometitulo);
        getContentPane().add(nicktitulo);
        getContentPane().add(premiotitulo);
        
        for(int i = 0;i<10;i++)
        {
            nome[i] = new JLabel("  "+qtdjogadores[i].getNome());
            nome[i].setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
            nome[i].setBackground(Color.red);
            nome[i].setOpaque(true);
            
            nick[i] = new JLabel("  "+qtdjogadores[i].getNickName());
            nick[i].setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
            nick[i].setBackground(Color.red);
            nick[i].setOpaque(true);
            
            premio[i] = new JLabel("  "+String.valueOf(qtdjogadores[i].getPremio()));
            premio[i].setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
            premio[i].setBackground(Color.red);
            premio[i].setOpaque(true);
            
            nome[i].setBounds(20, x, 150, 50);
            nick[i].setBounds(200, x, 150, 50);
            premio[i].setBounds(380, x, 150, 50);
            getContentPane().add(nome[i]);
            getContentPane().add(nick[i]);
            getContentPane().add(premio[i]);
            
            x=x+50;
        }
        
    }
    
}
